ctrl_interface=/run/wpa_supplicant
ap_scan=2

network={
        ssid="initramfs-ap"
        mode=2
        frequency=2412
        #psk=initramfs
        psk=36a5412941e59949e1e0573122989d36db3da26ca3e1ede20a0c224da185db23
}

