name: 360_uimage_uvc_upgrade

on:
  workflow_dispatch:

env:
  TAG_NAME: 360-uimage-uvc
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TERM: linux
  TZ: America/Los_Angeles
  CCACHE_DIR: /github/home/.ccache

jobs:
  build:
    name: build-uImage
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    container:
      image: debian:bookworm
    strategy:
      fail-fast: false
    steps:
      - name: Update package manager sources
        run: |
          apt-get update

      - name: Install build dependencies
        run: |
          apt-get install -y --no-install-recommends --no-install-suggests 7zip build-essential bc ccache cpio curl ca-certificates file git gh jq make gawk lzop procps rsync tzdata u-boot-tools unzip wget zip python3 

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v4
        with:
          install-only: true

      - name: Set timezone
        run: |
          ln -sf /usr/share/zoneinfo/${{ env.TZ }} /etc/localtime
          echo ${{ env.TZ }} > /etc/timezone
          DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -f noninteractive tzdata

      - name: Setup gh workspace to container
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout repository source
        uses: actions/checkout@v4
        with:
          ref: "master"
          fetch-depth: "1"

      - name: Setup cache directories
        run: |
          mkdir -p /github/home/.ccache

      - name: Restore build cache
        uses: actions/cache@v4
        if: always()
        with:
          path: /github/home/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ github.sha }}
            ${{ runner.os }}-ccache-

      - name: Download toolchain
        run: |
          curl -L https://github.com/themactep/thingino-firmware/releases/download/toolchain-x86_64/thingino-toolchain-x86_64_xburst1_uclibc_gcc15-linux-mipsel.tar.gz -o ~/thingino-toolchain_xburst1_uclibc_gcc15-linux-mipsel.tar.gz
          tar -xf ~/thingino-toolchain_xburst1_uclibc_gcc15-linux-mipsel.tar.gz -C ~/
          ~/mipsel-thingino-linux-uclibc_sdk-buildroot/relocate-sdk.sh

      - name: Configure ccache
        if: ${{ github.event.inputs.debug_enabled != 'true' }}
        shell: bash
        run: ccache -M 4G

      - name: Fetch U-Boot releases
        if: ${{ github.event.inputs.debug_enabled != 'true' }}
        shell: bash
        run: |
          mkdir -p initramfs/root
          #curl -L https://github.com/themactep/thingino-firmware/releases/latest/download/thingino-xiaomi_xiaofang_t20l_jxf23_rtl8189ftv.bin -o initramfs/root/u-boot-isvp_t20_sfcnor_lite.bin
          #truncate -s 262144 initramfs/root/u-boot-isvp_t20_sfcnor_lite.bin
          #curl -L https://github.com/themactep/thingino-firmware/releases/latest/download/thingino-wyze_cam3_t31x_gc2053_atbm6031.bin -o initramfs/root/u-boot-isvp_t31_sfcnor_ddr128M.bin
          #truncate -s 262144 initramfs/root/u-boot-isvp_t31_sfcnor_ddr128M.bin

      - name: Clone kernel repository
        if: ${{ github.event.inputs.debug_enabled != 'true' }}
        shell: bash
        run: |
          git clone --depth 1 https://github.com/gtxaspec/thingino-linux -b ingenic-t31
          cp kernel_configs/* thingino-linux/arch/mips/configs/
          cd kernel_configs/
          wget https://raw.githubusercontent.com/themactep/thingino-firmware/refs/heads/master/board/ingenic/xburst1/kernel/3.10.14/t31.generic.config
          cat t31.generic.config initramfs.config usb.config eth.config mmc.config wireless.config tools.config slim.config > ../thingino-linux/arch/mips/configs/isvp_360_t31_uvc_defconfig
          cd ..

      - name: Create initramfs root layout
        if: ${{ github.event.inputs.debug_enabled != 'true' }}
        shell: bash
        run: ./initramfs_create.sh

      - name: Build T20 kernel
        if: ${{ github.event.inputs.debug_enabled != 'true' }}
        shell: bash
        run: |
          export PATH="/github/home/mipsel-thingino-linux-uclibc_sdk-buildroot/bin:$PATH"
          cd thingino-linux
          make isvp_bull_mini_defconfig
          CROSS_COMPILE="ccache mipsel-linux-" make -j$(nproc) uImage
          cp arch/mips/boot/uImage.lzma /tmp/uImage.lzma-t20

      - name: Build T31 uImage.uvc
        if: ${{ github.event.inputs.debug_enabled != 'true' }}
        shell: bash
        run: |
          export PATH="/github/home/mipsel-thingino-linux-uclibc_sdk-buildroot/bin:$PATH"
          cd thingino-linux
          git apply ../kernel_patches/t31-mmc-remove-fix.patch
          make isvp_360_t31_uvc_defconfig
          CROSS_COMPILE="ccache mipsel-linux-" make -j$(nproc) uImage
          FILE_SIZE=$(stat -c %s "arch/mips/boot/uImage.lzma")
          MAX_SIZE=2097152
          if [ "$FILE_SIZE" -lt "$MAX_SIZE" ]; then
              cp arch/mips/boot/uImage.lzma /tmp/uImage.uvc-t31
              echo "Success, rename uImage.uvc-t31 to uImage.uvc and put it in sdcard to use it."
          else
              echo "Error: uImage.uvc can't be larger than 2048k (2097152), its now" $FILE_SIZE
              exit 1
          fi
          
          mkdir /tmp/t31sd
          cp -r ../sdcard /tmp/t31sd/
          cp arch/mips/boot/uImage.lzma /tmp/t31sd/sdcard/uImage.uvc


          cd /tmp/t31sd/sdcard/
          zip -r /tmp/360-t31-initramfs-sd.zip .
          cd -
          rm -rf /tmp/t31sd/

      - name: Build for motu k7ts t41nq nand
        if: ${{ github.event.inputs.debug_enabled != 'true' }}
        shell: bash
        run: |
          export PATH="/github/home/mipsel-thingino-linux-uclibc_sdk-buildroot/bin:$PATH"

          #change to t41
          rm -rf thingino-linux
          git clone --depth 1 https://github.com/gtxaspec/thingino-linux -b ingenic-t41-4.4.94

          cat ./kernel_configs/t41.generic.config ./kernel_configs/nand.fragment ./kernel_configs/initramfs_motu.config ./kernel_configs/tools.config  > thingino-linux/arch/mips/configs/isvp_motu_t41nq_nand_360_k7ts_defconfig
          cp ./kernel_patches/k7ts.dts ./thingino-linux/arch/mips/boot/dts/ingenic/marmot.dts

          #make nand env to load initramfs
          cp ./motu/env_tools_linux_x86 ./motu/k7ts/
          cp ./motu/motu-t41-nand-env.json ./motu/k7ts/nand-env.json
          cp ./motu/mtpt_nand_env.py ./motu/k7ts/
          cd ./motu/k7ts/
          ./env_tools_linux_x86 -b ./nand-env.json
          python3 ./mtpt_nand_env.py
          cd -


          #add busybox with more function.
          wget https://github.com/gtxaspec/wyze-neos-upgrade/raw/refs/heads/master/initramfs/bin/busybox
          cp ./busybox ./initramfs/bin/busybox
          upx -d ./initramfs/bin/busybox
          chmod 0755 ./initramfs/bin/busybox
          ./initramfs_create.sh

          cd thingino-linux
          make isvp_motu_t41nq_nand_360_k7ts_defconfig
          CROSS_COMPILE="ccache mipsel-linux-" make -j$(nproc) uImage

          mkdir /tmp/motusd
          cp -r ../motu/k7ts/sdcard/ /tmp/motusd/
          cp arch/mips/boot/uImage.lzma /tmp/motusd/sdcard/motu-t41-nand.uImage
          cp ../motu/k7ts/nand-env.mtpt /tmp/motusd/sdcard/update.mtpt


          cd /tmp/motusd/sdcard/
          zip -r /tmp/motu-360-k7ts-initramfs-sd.zip .
          cd -
          rm -rf /tmp/motusd/


      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: 360-uimage-uvc-upgrader
          path: |
            #/tmp/uImage.lzma-t20
            /tmp/uImage.uvc-t31
            /tmp/360-t31-initramfs-sd.zip
            /tmp/motu-360-k7ts-initramfs-sd.zip
